[package]
name = "kbdi"
version = "0.2.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
publish = false

[dependencies]
winapi = "0.2"
user32-sys = "0.2"
advapi32-sys = "0.2"
kernel32-sys = "0.2"

[dependencies.winreg]
version = "0.4"
default-features = false
features = []

[dependencies.clap]
version = "2.24.1"
default-features = false
features = []

[profile.release]
lto = true
